services:
  - type: web
    name: crop-disease-detector
    env: python
    plan: free
    # Move the version here:
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh